// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package litedb

type GasMigrations struct {
	Version        string
	Service        string
	Description    string
	MigrateVersion string
	ModuleVersion  string
	AppliedAt      string
	Dirty          int64
}
