// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package mydb

import (
	"context"
)

const getAppliedMigrations = `-- name: GetAppliedMigrations :many
SELECT version,
       service,
       description,
       migrate_version,
       module_version,
       applied_at,
       dirty
FROM __gas_migrations
ORDER BY version
`

func (q *Queries) GetAppliedMigrations(ctx context.Context) ([]GasMigrations, error) {
	rows, err := q.db.QueryContext(ctx, getAppliedMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GasMigrations
	for rows.Next() {
		var i GasMigrations
		if err := rows.Scan(
			&i.Version,
			&i.Service,
			&i.Description,
			&i.MigrateVersion,
			&i.ModuleVersion,
			&i.AppliedAt,
			&i.Dirty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirtyMigrations = `-- name: GetDirtyMigrations :many
SELECT version,
       service,
       description,
       migrate_version,
       module_version,
       applied_at,
       dirty
FROM __gas_migrations
WHERE dirty = TRUE
ORDER BY version
`

func (q *Queries) GetDirtyMigrations(ctx context.Context) ([]GasMigrations, error) {
	rows, err := q.db.QueryContext(ctx, getDirtyMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GasMigrations
	for rows.Next() {
		var i GasMigrations
		if err := rows.Scan(
			&i.Version,
			&i.Service,
			&i.Description,
			&i.MigrateVersion,
			&i.ModuleVersion,
			&i.AppliedAt,
			&i.Dirty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMigrationApplied = `-- name: MarkMigrationApplied :exec
INSERT INTO __gas_migrations (version, service, description, migrate_version, module_version)
VALUES (?, ?, ?, ?, ?)
`

type MarkMigrationAppliedParams struct {
	Version        string
	Service        string
	Description    string
	MigrateVersion string
	ModuleVersion  string
}

func (q *Queries) MarkMigrationApplied(ctx context.Context, arg MarkMigrationAppliedParams) error {
	_, err := q.db.ExecContext(ctx, markMigrationApplied,
		arg.Version,
		arg.Service,
		arg.Description,
		arg.MigrateVersion,
		arg.ModuleVersion,
	)
	return err
}

const markMigrationDirty = `-- name: MarkMigrationDirty :exec
INSERT INTO __gas_migrations (version, service, description, migrate_version, module_version, dirty)
VALUES (?, ?, ?, ?, ?, TRUE)
ON DUPLICATE KEY UPDATE dirty = TRUE
`

type MarkMigrationDirtyParams struct {
	Version        string
	Service        string
	Description    string
	MigrateVersion string
	ModuleVersion  string
}

func (q *Queries) MarkMigrationDirty(ctx context.Context, arg MarkMigrationDirtyParams) error {
	_, err := q.db.ExecContext(ctx, markMigrationDirty,
		arg.Version,
		arg.Service,
		arg.Description,
		arg.MigrateVersion,
		arg.ModuleVersion,
	)
	return err
}

const removeMigration = `-- name: RemoveMigration :exec
DELETE
FROM __gas_migrations
WHERE version = ?
`

func (q *Queries) RemoveMigration(ctx context.Context, version string) error {
	_, err := q.db.ExecContext(ctx, removeMigration, version)
	return err
}
